- name: Create a directory for scripts
  file:
    path: ~/scripts
    state: directory
    mode: '0755'

- name: Install Script Dependencies
  become: yes
  become_user: root
  become_method: sudo
  apt:
    update_cache: yes
    name: ['brightnessctl']
    state: latest
